### PR TITLE
add the minify plugin

### PR DESCRIPTION
**Pull request by eshaben**
This PR adds the minify plugin, which will minify all of the HTML, CSS, and JavaScript files. In order for this to work as intended, the `tanssi.css` file needs to be under the `extra_css` config in the `mkdocs.yml` file. With the css config updated there, we don't need to specify it in the `main.html` file

### CODE REVIEW

**Comment by eshaben** [comment]
To run this locally, refer to these instructions: https://github.com/papermoonio/moonbeam-mkdocs/pull/163#issuecomment-1909341816

**Comment by albertov19** [comment]
Hey @eshaben - When I try this out, the images in the index pages disappear. Check it out with the `build-docs-site` script and the following command:

```
./buildSite.sh -d tanssi -f  -m "main" -e "main" -o "moondance-labs"
```

**Comment by eshaben** [comment]
@albertov19 just need to merge the changes from the png > webp change. all good now!

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
