### PR TITLE
Changes for Expandable Function Parameter Details

### PR DESCRIPTION
**Pull request by themacexpert**
Screenshot 2024-02-01 at 9 34 36 PM

### CODE REVIEW

**Comment by eshaben** [comment]
@albertov19 expandable admonitions, like we do currently on the xcm pages on moonbeam docs

**Review by eshaben — COMMENTED** [review]
i think the admonition changes themself look good, but i'm going to push a couple commits to fix the teal background on the tabbed elements for text

**Comment by eshaben** [comment]
Made some updates and tested it with different types of content in the tabbed elements too to make sure it's all good.

Screenshot 2024-02-02 at 12 35 35 PM
Screenshot 2024-02-02 at 12 35 29 PM
Screenshot 2024-02-02 at 12 39 04 PM
Screenshot 2024-02-02 at 12 39 17 PM

**Review by albertov19 — APPROVED** [review]
LGTM!

**Pull request merged**
